# Configuración de la base de datos MongoDB
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=quarkus_db


# Configuración del puerto del servidor HTTP
quarkus.http.port=8080


# Configuración de JWT
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=quarkus_issuer
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem

jwt.access.duration=900
jwt.refresh.duration=604800
